#!/bin/sh
EPNOI_HOME="/JUNK/epnoi"

#First we initialize the directories
SCRIPT_DIR=$(pwd)

TMP_DIR=$EPNOI_HOME/tmp

SOLR_DIR=$EPNOI_HOME/"epnoideployment/solr"
CASSANDRA_DIR=$EPNOI_HOME/"epnoideployment/apache-cassandra-2.1.3"
VIRTUOSO_DIR="/usr/local/virtuoso-opensource"
VERBOSE_PARAMETER=$1

start_solr () {
echo "Starting SOLR!--------------------------------------------------------------------------------"
cd $SOLR_DIR
java -jar $SOLR_DIR/start.jar > $TMP_DIR/solr.output.log 2>&1 &
echo $! > $TMP_DIR/solr.pid
echo $!
cd $SCRIPT_DIR
}

start_cassandra () {
echo "Starting Cassandra!---------------------------------------------------------------------------"
$CASSANDRA_DIR/bin/cassandra -f $ > $TMP_DIR/cassandra.output.log 2>&1 &
echo $! > $TMP_DIR/cassandra.pid
echo $!
}

start_virtuoso () {
echo "Starting Virtuoso!---------------------------------------------------------------------------"
cd $VIRTUOSO_DIR/var/lib/virtuoso/db
$VIRTUOSO_DIR/bin/virtuoso-t -f > $TMP_DIR/virtuoso.output.log 2>&1 &
echo $! > $TMP_DIR/virtuoso.pid
echo $!
}

start_epnoi () {
echo "Starting epnoi!---------------------------------------------------------------------------"
cd $EPNOI_HOME/epnoi
if [ $VERBOSE_PARAMETER == "-v" ] 
then
	mvn jetty:run | tee $TMP_DIR/epnoi.output.log &
else
	mvn jetty:run > $TMP_DIR/epnoi.output.log 2>&1 &
fi

echo $! > $TMP_DIR/epnoi.pid 
echo $!
}

echo $SCRIPT_DIR
echo "Starting epnoi at $EPNOI_HOME" 

#Starting SOLR
if [ -e $TMP_DIR ]; then
	echo "The temporal directory has already been created. Run epnoi-stop first"
else
	echo "Creating the temporal directory"
	mkdir $TMP_DIR 
	start_solr
	start_cassandra
	start_virtuoso
	start_epnoi
fi



